spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

    # redis
    redis:
      host: 192.168.171.133
      port: 6379
      database: 0
      timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          #最大阻塞等待时间(负数表示没限制)
          max-idle: 5
          min-idle: 0
    # nacaos
    cloud:
      nacos:
        discovery:
          username: nacos
          password: nacos
          server-addr: 127.0.0.1:8848
          namespace: 2200cc0d-7d2f-4fab-9d2e-b282cae54c62
#        config:
#          username: nacos
#          password: nacos
#          server-addr: 127.0.0.1:8848
#          namespace: 2200cc0d-7d2f-4fab-9d2e-b282cae54c62
    #返回json的全局时间格式
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd  HH:mm:ss
    #配置mapper xml文件的路径
  mybatis-plus:
    mapper-locations: classpath:mapper/**.xml
    #mybatis日志
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl