server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  redis:
    host: 192.168.171.133
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: 2200cc0d-7d2f-4fab-9d2e-b282cae54c62

    # gateway 配置
    gateway:
      discovery:
        locator:
          enabled: true #使用服务发现路由（开启从注册中心动态创建路由的功能，利用微服务名进行路由)
      globalcors:
        # 全局允许跨域访问
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins-pattern: "*"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
#      routes:
#        - id: jianli-service-goods
#          uri: lb://jianli-service-goods
#          predicates:
#            - Path=/api/goods/**
#          filters:
#            - StripPrefix=2
#        - id: jianli-service-build
#          uri: lb://jianli-service-build
#          predicates:
#            - Path=/api/build/**
#          filters:
#            - StripPrefix=2
#        - id: jianli-service-iot
#          uri: lb://jianli-service-iot
#          predicates:
#            - Path=/api/iot/**
#          filters:
#            - StripPrefix=2
